"""add lazy loading

Revision ID: 9dac3c922985
Revises: 69acaa179443
Create Date: 2025-03-11 15:08:35.706269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dac3c922985'
down_revision = '69acaa179443'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
